




[custom]

## direct mode
ruleset=DIRECT,geoip-cn+https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/cncidr.txt
ruleset=DIRECT,geosite-cn+https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/direct.txt
ruleset=DIRECT,private+https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/private.txt

## block mode
# ruleset=block,category-ads-all+https://github.com/3zsvvev7/mini_rule_set/raw/master/blocked.srs
# ruleset=block,geosite-category-ads-all+https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-category-ads-all.srs
# ruleset=block,geosite-malware+https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-malware.srs
# ruleset=block,geosite-phishing+https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-phishing.srs

## proxy mode
ruleset=Select,GFW+https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/gfw.txt
ruleset=Select,geosite-!cn+https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/tld-not-cn.txt
ruleset=Select,Telegram-IPS+https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/telegramcidr.txt
#ruleset=🎯 Global,[]GEOIP,CN

## final路由
ruleset=Select,[]FINAL

custom_proxy_group=Select`select`[]Auto`[]DIRECT`.*
custom_proxy_group=Auto`url-test`.*`http://connectivitycheck.platform.hicloud.com/generate_204`300,,50
#custom_proxy_group=🎯 Direct`select`[]direct
#custom_proxy_group=🛑 Block`select`[]REJECT`[]direct

enable_rule_generator=true
overwrite_original_rules=true
