name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - ".github/**"
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

env:
  image: subconv
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.image}}:latest
    - name: Export image
      run: |
        docker save -o ${{env.image}}.tar ${{env.image}}:latest
    - uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        # ssh remote host
        host: ${{ vars.SUBCONV_HOST }} # optional
        # ssh remote port
        port: ${{ vars.SUBCONV_PORT }} # optional, default is 22
        # ssh user
        user: ${{ secrets.SUBCONV_SSH_USER }} # optional
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        pass: ${{ secrets.SUBCONV_SSH_PASS }} # optional
        # execute commands before SCP
        first_ssh: |
          [ -n "`docker ps -a | grep subconv`" ] && docker rm -f subconv;  
          [ -n "`docker images 2>/dev/null | grep subconv`" ] && docker rmi -f subconv;
          [ -f /tmp/${{env.image}}.tar ] && rm /tmp/${{env.image}}.tar;
          true
        # scp local and remote
        scp: |
          ./${{env.image}}.tar => /tmp/
        # execute commands after SCP
        last_ssh: |
          docker load -i /tmp/${{env.image}}.tar 
          docker run -d -p 25500:25500 --name ${{env.image}} --restart=always ${{env.image}}:latest