name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  image: subconv
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.image}}:latest
    - name: Export image
      run: |
        docker save -o ${{env.image}}.tar ${{env.image}}:latest
    - uses: alinz/ssh-scp-action@v0.1.2
      with:
        # ssh remote host
        host: ${{vars.SUBCONV_HOST}} # optional
        # ssh remote port
        port: ${{vars.SUBCONV_PORT}} # optional, default is 22
        # ssh user
        user: ${{secrets.SUBCONV_SSH_USER}} # optional
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{secrets.SUBCONV_SSH_PRIVATE_KEY}} # optional
        # execute commands before SCP
        ssh_before: docker rm -f subconv && docker rmi -f subconv && rm /tmp/${{env.image}}.tar
        # scp local and remote
        scp: -P ${{vars.SUBCONV_PORT}} ${{env.image}}.tar ${{secrets.SUBCONV_SSH_USER}}@${{vars.SUBCONV_HOST}}:/tmp/${{env.image}}.tar # optional
        # execute commands after SCP
        ssh_after: docker load -i /tmp/${{env.image}}.tar && docker run -d -p 25500:25500 --restart=alwasy ${{env.image}}:latest